import type { NextPage } from "next";
import Head from "next/head";
import NewTask from "../src/components/newTask/NewTask";
import Task from "../src/components/task/Task";

const Home: NextPage = () => {
  return (
    <div className="mx-auto text-dark-500">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-orange-500 text-5xl font-bold text-center mt-28">
          Today&rsquo;s focus
        </h1>

        <div className="tasks mt-4">
          <Task
            tasks={[
              { title: "Write monthly newsletter", isDone: false },
              { title: "Tweet planning for the week", isDone: false },
            ]}
          />
        </div>
      </div>
      <div>
        <h2 className="text-dark-200 text-4xl font-bold text-center mt-28">
          Done
        </h2>
        <div className="tasks mt-4">
          <Task tasks={[{ title: "Call mom", isDone: true }]} />
        </div>
      </div>
      <NewTask />
    </div>
  );
};

export default Home;
